In [69]:
import pandas as pd
import numpy as np
import json

asinToIndex = {}
index = 0
scoreMatrix = []
chunks = pd.read_json(
    '../Dataset/Books.json', lines=True, chunksize=10000, 
    typ="frame", orient="records", dtype={"asin": str, "overall": int}
)

for chunk in chunks:
    for _, row in chunk.iterrows():
        asin = row["asin"]
        rate = row["overall"]

        if (asin not in asinToIndex):
            scoreMatrix.append([0,0,0,0,0])
            asinToIndex[asin] = index
            index += 1

        row = asinToIndex[asin]
        scoreMatrix[row][rate-1] += 1

scoreMatrix = np.array(scoreMatrix)
print(scoreMatrix)

[[  6   4   8  15 173]
 [  0   4   2  10   2]
 [  1   0   0   2  13]
 ...
 [  0   0   0   1  12]
 [  0   0   0   1  29]
 [  0   0   0   1   6]]


In [72]:
avgRatings = (np.average(scoreMatrix, axis=1, weights=[1,2,3,4,5]) * 15) / (np.sum(scoreMatrix, axis=1))
print(avgRatings)

[4.67475728 3.55555556 4.625      ... 4.92307692 4.96666667 4.85714286]
